name: "AccountsSecurity"
version: "1.0.0"
main: "AccountsSecurity"
api: "5.0.0"

website: "https://vk.com/bedrocktimestudio"
author: "BedrockTimeStudio"

load: "STARTUP"
# https://github.com/MEFRREEX/FormConstructor-PM
depend: ["FormConstructor"]
